//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: hello

package hello

import "github.com/google/flatbuffers/go"

import (
  context "golang.org/x/net/context"
  grpc "google.golang.org/grpc"
)

// Client API for Greeter service
type GreeterClient interface{
  Say(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* Response, error)  
}

type greeterClient struct {
  cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
  return &greeterClient{cc}
}

func (c *greeterClient) Say(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* Response, error) {
  out := new(Response)
  err := grpc.Invoke(ctx, "/hello.Greeter/Say", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for Greeter service
type GreeterServer interface {
  Say(context.Context, *Request) (*flatbuffers.Builder, error)  
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
  s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Say_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(Request)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(GreeterServer).Say(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/hello.Greeter/Say",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(GreeterServer).Say(ctx, req.(* Request))
  }
  return interceptor(ctx, in, info, handler)
}


var _Greeter_serviceDesc = grpc.ServiceDesc{
  ServiceName: "hello.Greeter",
  HandlerType: (*GreeterServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Say",
      Handler: _Greeter_Say_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

